addon: 
  - name: calico
    chart: tigera-operator
    repoURL: https://docs.tigera.io/calico/charts
    targetRevision: v3.33.0
    namespace: tigera-operator
    helmValues: |
      installation:
        kubernetesProvider: Kind
        cni:
          type: Calico
        calicoNetwork:
          bgp: Disabled
          ipPools:
            - allowedUses:	
                - Workload	
                - Tunnel	
              assignmentMode: Automatic	
              blockSize: 26	
              cidr: 10.244.0.0/16	
              disableBGPExport: false	
              disableNewAllocations: false	
              encapsulation: IPIP	
              name: default-ipv4-ippool	
              natOutgoing: Enabled	
              nodeSelector: all()