addon: 
  - name: openunison
    chart: openunison-operator
    repoURL: https://nexus.tremolo.io/repository/helm
    targetRevision: 3.0.31
    namespace: openunison
    helmValues: |
      openunison:
        auto_timestamp: false
        force_update: initial-deployment
  - name: openunison-orchestra
    chart: orchestra
    helmValues: |
      network:
        openunison_host: "k8sou.localhost"
        dashboard_host: "k8sdb.localhost"
        api_server_host: "k8sapi.localhost"
    repoURL: https://nexus.tremolo.io/repository/helm
    targetRevision: 3.1.56
    namespace: openunison
  - name: openunison-portal
    chart: orchestra-login-portal
    helmValues: |
      network:
        openunison_host: "k8sou.localhost"
        dashboard_host: "k8sdb.localhost"
        api_server_host: "k8sapi.localhost"
    repoURL: https://nexus.tremolo.io/repository/helm
    targetRevision: 2.3.98