addon: 
  - name: openunison
    chart: openunison-operator
    repoURL: https://nexus.tremolo.io/repository/helm
    targetRevision: 3.0.31
    namespace: openunison
    helmValues: |
      openunison:
        auto_timestamp: false
        force_update: initial-deployment
      network:
        gatewayapi:
          class: envoy
          gateway:
            # disable the creation of the Gateway object
            create: false
            # specify the parent_refs for the web components of OpenUnison
            parent_refs:
              - group: gateway.networking.k8s.io
                kind: Gateway
                name: envoy-gateway
                namespace: envoy-gateway-system
                sectionName: http      
  - name: openunison-orchestra
    chart: orchestra
    helmValues: |
      network:
        openunison_host: "k8sou.localhost"
        dashboard_host: "k8sdb.localhost"
        api_server_host: "k8sapi.localhost"
    repoURL: https://nexus.tremolo.io/repository/helm
    targetRevision: 3.1.56
    namespace: openunison
  - name: openunison-portal
    chart: orchestra-login-portal
    helmValues: |
      network:
        openunison_host: "k8sou.localhost"
        dashboard_host: "k8sdb.localhost"
        api_server_host: "k8sapi.localhost"
    repoURL: https://nexus.tremolo.io/repository/helm
    targetRevision: 2.3.98
    namespace: openunison