apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keda
  namespace: argocd
spec:
  project: default
  ignoreDifferences:
    - group: argoproj.io
      kind: Application
      jsonPointers:
        - /status
  source:
    chart: keda
    repoURL: https://kedacore.github.io/charts
    targetRevision: 2.21.0
    helm:
      valuesObject:
        serviceMonitor:
          enabled: false
        resources:
          limits:
            cpu: 300m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
  destination:
    namespace: keda
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
