# Todo: move to crds folder? Can add KEDA and Envoy crds to this workflow
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: calico-crds
#   namespace: argocd
# spec:
#   project: default
#   source:
#     repoURL: https://github.com/chhayham/k8s-envoy-gateway
#     targetRevision: 2026-10-02-83df44 #main
#     path: deploy/argocd-applications/calico/crds
#   destination:
#     namespace: calico
#     server: https://kubernetes.default.svc
#   syncPolicy:
#     syncOptions:
#     - CreateNamespace=true
#     - ServerSideApply=true
#     automated:
#       prune: true
#       selfHeal: true
--- 
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-addons
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - matrix:
      generators:
      - git:
          repoURL: https://github.com/chhayham/k8s-envoy-gateway
          revision: 2026-10-02-83df44 #main
          files:
          - path: deploy/argocd-applications/**/*config.yaml
      - list:
          elementsYaml: "{{ .addon | toJson }}"
  template:
    metadata:
      name: '{{.name}}'
      namespace: argocd
    spec:
      project: default
      source:
        chart: '{{.chart}}'
        repoURL: '{{.repoURL}}'
        targetRevision: '{{.targetRevision}}'
        helm:
          values: |
            {{.helmValues}}
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{.namespace}}'
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
---
# Deploy gatewayclass, gateway, and httproute for envoy gateway
# Todo: create helm chart for gatewayclass and gateway?  Then it can be added to addons applicationset
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: envoy-gatewayclass
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/chhayham/k8s-envoy-gateway
    targetRevision: 2026-10-02-83df44 #main
    path: deploy/argocd-applications/envoy-gateway-system/gatewayclass
  destination:
    namespace: envoy-gateway-system
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
--- 
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: openunison-secret
#   namespace: argocd
# spec:
#   project: default
#   source:
#     repoURL: https://github.com/chhayham/k8s-envoy-gateway
#     targetRevision: 2026-10-02-83df44 #main
#     path: deploy/argocd-applications/openunison/secret
#   destination:
#     namespace: openunison
#     server: https://kubernetes.default.svc
#   syncPolicy:
#     syncOptions:
#     - CreateNamespace=true
#     - ServerSideApply=true
#     automated:
#       prune: true
#       selfHeal: true
--- 
# Todo: create helm chart for httproute?  Then it can be added to addons applicationset
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-addons-httproute
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/chhayham/k8s-envoy-gateway
        revision: 2026-10-02-83df44 #main
        files:
        - path: deploy/httproute/*
  template:
    metadata:
      name: '{{.path.basename}}-httproute'
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/chhayham/k8s-envoy-gateway
        targetRevision: 2026-10-02-83df44 #main
        path: '{{.path.path}}'
      destination:
        namespace: '{{.path.basename}}'
        server: https://kubernetes.default.svc
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true
        automated:
          prune: true
          selfHeal: true
