addon: 
  - name: envoy-gateway-system
    chart: gateway-helm
    repoURL: docker.io/envoyproxy
    targetRevision: v1.9.1
    namespace: envoy-gateway-system
    helmValues: |
      crds:
        enabled: false
      config:
      # -- EnvoyGateway configuration. Visit https://gateway.envoyproxy.io/docs/api/extension_types/#envoygateway to view all options.
        envoyGateway:
          gateway:
            controllerName: gateway.envoyproxy.io/gatewayclass-controller
          provider:
            type: Kubernetes
          logging:
            level:
              default: info
          extensionApis:
            enableBackend: true
