apiVersion: v1
type: Opaque
metadata:
  name: orchestra-secrets-source
  namespace: openunison
data:
  # only needed if the kubernetes dashboard is enabled
  K8S_DB_SECRET: cGFzc3dvcmQ=
  unisonKeystorePassword: cGFzc3dvcmQ=
  GITHUB_SECRET_ID: "****"
kind: Secret